name: Deploy Frontend
on:
  push:
    branches: [dev, homolog, main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Set branch env
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Display deploy info
        run: |
          echo " Deploying branch: ${{ env.BRANCH }}"
          echo " Runner: self-hosted"
          echo " Script: /home/guilherme/edital/deploy-frontend.sh"

      - name: Execute deploy script
        run: bash /home/guilherme/edital/deploy-frontend.sh ${{ env.BRANCH }}

      - name: Deploy completed
        run: echo " Deploy completed for ${{ env.BRANCH }}"
